[Zadanie #35933][Social App] Pobieranie feed'u i wyświetlanie go na stronie Home dla niezalogowanego użytkownika
ulajeziorna20/social-app-dev pull request #4
Opened 2022-03-23 08:23 UTC by ulajeziorna20

2022-04-01 07:29 UTC, arena108 reviewed
Nie ma w zależnościach axiosa
Dodaj go.

npm install axios --save

i wtedy ponownie do review

i linter ci błędy zwraca
\social-app-dev\src\components\feed\feed-no-login\FeedNoLogin.js
  18:21  warning  'userIndex' is assigned a value but never used. Allowed unused vars must match /^_/u  unused-imports/no-unused-vars
---
i jest masa console.log'ów...

2022-04-04 07:27 UTC, arena108 reviewed
wymień getDate

2022-04-04 07:27 UTC, arena108 commented on src/components/feed/feed-no-login/FeedNoLogin.js
> +  const getDate = () => {
getData -> :)

2022-04-05 08:53 UTC, arena108 commented
I proszę o ujednolicenie tematu PR. Ma być wg. takiego samego wzorca jak poprzednie np. "[Social 36774][Social App] Logowanie. Przez podstronę, Popup'a, cała procedura."

2022-06-16 09:58 UTC, arena108 commented on src/App.js
> +      {/* <footer className='footer'>© 2022 by Jeziorna Urszula Inc.</footer> */}
komentarz w kodzie został

2022-06-16 10:00 UTC, arena108 commented on src/components/feed/feed-no-login/FeedNoLogin.js
> +  useEffect(() => {
useEffect trzyma w jednym miejscu, przerzuć to pod linię 45.

2022-06-16 10:29 UTC, arena108 commented on src/components/feed/feed-no-login/FeedNoLogin.js
> +        setLoading(true)
tutaj setLoading(false) powinno być, do doładowanie się tutaj kończy.
Za to nie masz nigdzie startu ładowania

2022-06-16 10:29 UTC, arena108 commented on src/components/feed/feed-no-login/FeedNoLogin.js
> +    axios
przed wywołaniem axiosa powinien być start ładowania setLoading(true)

2022-06-16 10:36 UTC, arena108 commented
Zainstaluj sobie pakiet https://www.npmjs.com/package/eslint-plugin-react-hooks jako pakiet dev.

I dodaj regułę w .eslintrc.js 

'react-hooks/exhaustive-deps': 'warn',

zaraz pod linią 

'react-hooks/rules-of-hooks': 'error',

Będzie ci podpowiadać, których dependencji np. w useEffect ci brakuje

2022-06-16 10:56 UTC, arena108 requested changes
Ogólnie ładnie, popraw jeszcze te kilka rzeczy i mergujemy

2022-06-16 13:09 UTC, arena108 approved these changes

2022-06-16 13:10 UTC, arena108 approved these changes
jest ok

2022-06-16 13:11 UTC, hansbot-108 approved these changes

2022-06-16 13:12 UTC, merged